apm-server:
  host: "0.0.0.0:8200" 

output.elasticsearch:
  hosts: ["https://elasticsearch:9200"]
  api_key: "${ELASTICSEARCH_API_KEY}"
  ssl: 
    verification_mode: certificate
    certificate_authorities: ["/usr/share/apm-server/http_ca.crt"]