filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /app/logs/*.json
  json.keys_under_root: true
  json.overwrite_keys: true

processors:
  - add_fields:
      target: ''
      fields:
        environment: production

output.elasticsearch:
  hosts: ["https://192.168.45.179:9200"]
  api_key: "${ELASTICSEARCH_API_KEY}"
  ssl:
    certificate_authorities: ["/usr/share/filebeat/http_ca.crt"]