version: "3.8"

services:
  # MySQL Database service
  mysql:
    image: mysql:8.0.34
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306" #  MySQL container port 3306 mapped to host's 3307
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Mounting the init.sql script inorder to create 4 databases.
    networks:
      - app-network

  # Redis Cache service
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6380:6379" # Redis container port 6379 mapped to host's 6380
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
